version: "3"
services:
#  mysql:
#    build: ./mysql8.0
#    container_name: mysql8
#    ports:
#      - 3306:${MYSQL_PORT}
#    environment:
#      - MYSQL_DATABASE=${MYSQL_DB}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PSW}
#      - TZ=UTC
#    volumes:
#      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
#      - ./mysql8.0/logs:/var/log/mysql:rw
#      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
#      - ./common:/app:ro
#    networks:
#      - frontend
#      - backend

  p10user:
    build:
      context: ./p10user
      args:
        work_path: /go/src/app
    container_name: p10user
    ports:
      - 50000:50000
    volumes:
      - ./p10user:/go/src/app
    command: >
      sh -c "
        go run src/main.go
      "
    networks:
      - backend

#  consul1:
#    image: consul:latest
#    container_name: consul1
#    restart: always
#    ports:
#      - 8500:8500
#      - 8600:8600
#    command: consul agent -server  -dev -bind=127.0.0.1 -bootstrap-expect=1 -node=consul1 -client 0.0.0.0
#    networks:
#      - frontend
#      - backend
#
#
#
#
#  adminer:
#    build: ./docker-adminer/4
#    ports:
#      - 8080:${ADMINER_PORT}
#    networks:
#      - frontend
#      - backend


# todo : auto migrate
#  RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.4.0/migrate.linux-amd64.tar.gz | tar xvz \
#  && mv migrate.linux-amd64 /bin/migrate
# migrate -path ./migration -database mysql://root:${MYSQL_ROOT_PSW}@tcp\(mysql8:3306\)/${MYSQL_DB} up && \
# error: dial tcp 192.168.0.2:3306: connect: connection refused
# use :
# migrate -path ./migration -database mysql://root:1234@tcp\(127.0.0.1:3306\)/translate up


networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  mysql:
    driver: "local"
  p10user:
    driver: "local"
  adminer:
    driver: "local"
  consul1:
    driver: "local"

