version: "3"
services:

### mysql ########################################
  mysql:
    build:
      context: ./mysql
      args:
      - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
    - mysql:/var/lib/mysql
    - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
    - "${MYSQL_PORT}:3306"
    networks:
    - backend

### Adminer ###########################################
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - backend

### RabbitMQ #############################################
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    hostname: laradock-rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - backend


###################################### Services ########################################
########################################################################################

  p005api:
    build:
      context: ./p005api
    ports:
    - 81:81
    volumes:
    - ./p005api:/go/src/app
    networks:
    - backend  

  p010user:
    build:
      context: ./p010user
      args:
        work_path: /go/src/app
    ports:
      - 6010:6010
    volumes:
      - ./p010user:/go/src/app
    depends_on:
      - rabbitmq
    networks:
      - backend

  p012dict:
    build:
      context: ./p012dict
      args:
        work_path: /go/src/app
    ports:
      - 6012:6012
    volumes:
      - ./p012dict:/go/src/app
    command: >
      sh -c "
        go run src/main.go
      "
    networks:
      - backend

  p013keep:
    build:
      context: ./p013keep
      args:
        work_path: /go/src/app
    ports:
      - 6013:6013
    volumes:
      - ./p013keep:/go/src/app
    command: >
      sh -c "
        go run src/main.go
      "
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

volumes:
  mysql:
    driver: local
  rabbitmq:
    driver: local