version: "3"
services:
#  mysql:
#    build: ./mysql8.0
#    container_name: mysql8
#    ports:
#      - 3306:${MYSQL_PORT}
#    environment:
#      - MYSQL_DATABASE=${MYSQL_DB}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PSW}
#      - TZ=UTC
#    volumes:
#      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
#      - ./mysql8.0/logs:/var/log/mysql:rw
#      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
#      - ./common:/app:ro
#    networks:
#      - frontend
#      - backend

  # consul server
  consul001:
    image: consul
    command: >
      sh -c "
        consul agent -server -data-dir /tmp/node1 -node=consul001  -bootstrap-expect=1  -bind=0.0.0.0 -client=0.0.0.0 -ui
      "
    ports:
    - 8500:8500
    networks:
    - backend


  # consul client
  consul002:
    image: consul
    depends_on:
    - consul001
    command: >
      sh -c "
        consul agent \
        -data-dir /tmp/node2 \
        -node=consul002 \
        -retry-join=consul001 \
        -bind=0.0.0.0 \
        -client=0.0.0.0 \
        -config-dir /consul/config/ \
        -enable-local-script-checks
      "
    volumes:
    - ./consul/config:/consul/config
    networks:
    - backend

  p005api:
    build:
      context: ./p005api
      args:
        work_path: /go/src/app
    ports:
    - 80:8080
    volumes:
    - ./p005api:/go/src/app
    - ./pb:/go/src/pb
    command: >
      sh -c "
        go run src/main.go
      "
    networks:
    - backend  

  p010user:
    build:
      context: ./p010user
      args:
        work_path: /go/src/app
    ports:
      - 6010:6000
    volumes:
      - ./p010user:/go/src/app
      - ./pb:/go/src/app/src/pb
    command: >
      sh -c "
        ls /go/src/app/src/pb/p010user/ && \
        go run src/main.go
      "
    networks:
      - backend




#  adminer:
#    build: ./docker-adminer/4
#    ports:
#      - 8080:${ADMINER_PORT}
#    networks:
#      - frontend
#      - backend


# todo : auto migrate
#  RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.4.0/migrate.linux-amd64.tar.gz | tar xvz \
#  && mv migrate.linux-amd64 /bin/migrate
# migrate -path ./migration -database mysql://root:${MYSQL_ROOT_PSW}@tcp\(mysql8:3306\)/${MYSQL_DB} up && \
# error: dial tcp 192.168.0.2:3306: connect: connection refused
# use :
# migrate -path ./migration -database mysql://root:1234@tcp\(127.0.0.1:3306\)/translate up


networks:
  backend:
    driver: "bridge"


