apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trans-microsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trans-microsvc
  template:
      metadata:
        labels:
          app: trans-microsvc
      spec:
        containers:
          - name: p005api
            image: yw4code/trans-p005api:latest
            ports:
              - containerPort: 81
          - name: p010user
            image: yw4code/trans-p010user:latest
            ports:
              - containerPort: 6000

