apiVersion: apps/v1
kind: Deployment
metadata:
  name: trans-microsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trans-microsvc
  template:
    metadata:
      labels:
        app: trans-microsvc
    spec:
      containers:
        - name: p005api
          image: gcr.io/translate-1508946408545/p005api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 81
        - name: p010user
          image: gcr.io/translate-1508946408545/p010user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6010
        - name: p012dict
          image: gcr.io/translate-1508946408545/p012dict:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6012
        - name: p013keep
          image: gcr.io/translate-1508946408545/p013keep:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6013
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: trans-microsvc
  ports:
    - name: http
      protocol: TCP
      port: 81
      targetPort: 81
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trans-msvc
spec:
  rules:
    - http:
        paths:
          - path: /api/*
            backend:
              serviceName: api
              servicePort: 81